export {
  METALAYER_CONFIG_VERSION,
  MetaLayerConfigSchema,
  LocalizationPreferencesSchema,
  IdentityPreferencesSchema,
  MergeDefinitionSchema,
  RotationDefinitionSchema,
  RuleContextSchema,
  RuleSetSchema,
  SortingFieldSchema,
  SortingCriterionSchema,
  SortingPlanSchema,
  ResolvableFieldSchema,
  FieldProvidersSchema,
  DEFAULT_FIELD_PROVIDERS,
  CatalogDefinitionSchema,
  createDefaultMetaLayerConfig,
  parseMetaLayerConfig,
  type MetaLayerConfig,
  type LocalizationPreferences,
  type IdentityPreferences,
  type MergeDefinition,
  type RotationDefinition,
  type RuleContext,
  type RuleSet,
  type SortingField,
  type SortingCriterion,
  type SortingPlan,
  type ResolvableField,
  type FieldProviders,
  type CatalogDefinition,
} from './schema.js';

export {
  LegacyAddonConfigSchema,
  parseLegacyAddonConfig,
  listLegacySecretsPresent,
  LEGACY_SECRET_KEYS,
  type LegacyAddonConfig,
} from './legacy.js';

export {
  parseLegacyImportSource,
  planLegacyImport,
  toPublicImportPlan,
  type LegacyImportAttentionItem,
  type LegacyImportReport,
  type LegacyImportPlan,
} from './legacy-import.js';

export {
  compressToEncodedURIComponent,
  decompressFromEncodedURIComponent,
} from './lz-string.js';

export {
  LegacyManifestSchema,
  CatalogResponseSchema,
  EmptyCatalogResponseSchema,
  assertEmptyCatalogResponse,
  LegacySyntheticEmptyMetaSchema,
  LegacySyntheticEmptyCatalogSchema,
  MetaResponseSchema,
  assertNotFakeErrorCatalog,
  type LegacyManifest,
  type CatalogResponse,
  type MetaResponse,
} from './stremio-contracts.js';

export {
  LocalePreferenceSchema,
  RegionPreferenceSchema,
  ResolutionStrategySchema,
  EpisodeOrderTypeSchema,
  ArtworkTypeSchema,
  ResolutionStepSchema,
  FieldResolutionPlanSchema,
  MediaResolutionConfigSchema,
  ResolutionConfigSchema,
  parseResolutionConfig,
  planFromProviderChain,
  resolutionConfigFromFieldProviders,
  defaultResolutionConfig,
  getPlanForField,
  type LocalePreference,
  type RegionPreference,
  type ResolutionStrategy,
  type ResolutionStep,
  type FieldResolutionPlan,
  type MediaResolutionConfig,
  type ResolutionConfig,
} from './resolution.js';
